((DstIpAddr = dns) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3) ∧ (Proto = ICMP))
((DstPt = unknown_port) ∧ (Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (Flags = RST-PSH-ACK)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-SYN-ACK)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((Proto = IGMP)) ⇒ ((DstIpAddr = public_p2p) ∧ (DstPt = 0) ∧ (Flags = none) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((Flags = RST-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((Flags = SYN-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((SrcPt = 993)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p))
((Flags = FIN-ACK)) ⇒ ((Proto = TCP))
((DstIpAddr = dns)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = FIN-RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((Flags = PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = SYN-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = public_p2p)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = dns) ∧ (Flags = FIN-ACK)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstIpAddr = dns) ∧ (Proto = ICMP)) ⇒ ((DstPt = 3))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-SYN-RST-ACK)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((Flags = RST) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = dns) ∧ (Flags = SYN-PSH-ACK)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((Flags = FIN-SYN-RST-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p) ∧ (DstPt = 80) ∧ (SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstPt = 3))
(SrcIpAddr ≠ private_broadcast)
((Flags = FIN-SYN-RST-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = 80) ∧ (Flags = SYN-RST-PSH-ACK)) ⇒ ((DstIpAddr = public_p2p))
((Flags = FIN-RST-PSH-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = unknown_port) ∧ (Flags = SYN-RST-ACK)) ⇒ ((DstIpAddr = private_p2p) ∧ (SrcIpAddr = public_p2p))
((Flags = ACK) ∧ (SrcPt = 22)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 993)) ⇒ ((DstIpAddr = private_p2p) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = FIN-SYN-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = public_p2p) ∧ (Flags = RST)) ⇒ ((SrcPt = unknown_port))
((Flags = RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstPt = 80))
((DstPt = unknown_port) ∧ (Proto = UDP) ∧ (SrcIpAddr = public_p2p)) ⇒ ((SrcPt = unknown_port))
((SrcIpAddr = public_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = dns) ∧ (Proto = UDP)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((Flags = SYN-ACK)) ⇒ ((Proto = TCP))
((Flags = SYN-RST-ACK)) ⇒ ((Proto = TCP))
((Flags = FIN-SYN-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p) ∧ (SrcPt = unknown_port))
((Flags = FIN-SYN-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = 80) ∧ (Flags = FIN-SYN-ACK)) ⇒ ((DstIpAddr = public_p2p))
((SrcPt = 68)) ⇒ ((DstPt = 67) ∧ (Flags = none) ∧ (Proto = UDP))
((Flags = RST-ACK)) ⇒ ((Proto = TCP))
((Flags = FIN-SYN-ACK)) ⇒ ((Proto = TCP))
((Flags = FIN-RST-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((DstPt = 22)) ⇒ ((Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((SrcIpAddr = public_p2p)) ⇒ ((DstIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (Flags = SYN-RST-ACK)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((DstPt = unknown_port) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (Flags = SYN-RST-PSH-ACK)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (Flags = none) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((Flags = FIN-SYN-RST-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((Flags = FIN-SYN-PSH-ACK)) ⇒ ((Proto = TCP))
((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = FIN-SYN-RST-PSH-ACK)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-SYN-ACK)) ⇒ ((SrcPt = unknown_port))
((DstPt = 3)) ⇒ ((Flags = none) ∧ (Proto = ICMP) ∧ (SrcPt = 0))
((DstIpAddr = public_p2p) ∧ (Flags = SYN-ACK)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = SYN-RST-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((DstPt = 22) ∧ (Flags = ACK)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 53) ∧ (Flags = none)) ⇒ ((Proto = UDP))
((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcIpAddr = private_p2p)) ⇒ ((Proto = TCP))
((DstPt = unknown_port) ∧ (Flags = FIN-SYN-RST-ACK)) ⇒ ((DstIpAddr = private_p2p) ∧ (SrcIpAddr = public_p2p))
((DstPt = 68)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 67))
((Flags = PSH-ACK)) ⇒ ((Proto = TCP))
((Flags = SYN-RST-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p) ∧ (SrcPt = unknown_port))
((Flags = FIN-RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
(Flags ≠ FIN) ∧ (Flags ≠ FIN-SYN) ∧ (Flags ≠ FIN-RST) ∧ (Flags ≠ FIN-SYN-RST) ∧ (Flags ≠ PSH) ∧ (Flags ≠ FIN-PSH) ∧ (Flags ≠ SYN-PSH) ∧ (Flags ≠ FIN-SYN-PSH) ∧ (Flags ≠ RST-PSH) ∧ (Flags ≠ FIN-RST-PSH) ∧ (Flags ≠ SYN-RST-PSH) ∧ (Flags ≠ FIN-SYN-RST-PSH)
((Flags = SYN)) ⇒ ((DstIpAddr = public_p2p) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((Flags = SYN-RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((DstIpAddr = public_p2p) ∧ (SrcIpAddr = private_p2p))
((DstPt = 443)) ⇒ ((DstIpAddr = public_p2p) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-RST-ACK)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((Flags = SYN-RST-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((DstIpAddr = public_p2p) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = public_p2p) ∧ (Proto = UDP) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = private_broadcast)) ⇒ ((Flags = none) ∧ (Proto = UDP))
((DstPt = 80) ∧ (Flags = FIN-PSH-ACK)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 80) ∧ (Flags = RST-PSH-ACK)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 80) ∧ (Flags = FIN-RST-PSH-ACK)) ⇒ ((DstIpAddr = public_p2p))
((Flags = none) ∧ (SrcPt = unknown_port)) ⇒ ((Proto = UDP))
((Flags = RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = FIN-SYN-RST-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((DstIpAddr = public_p2p) ∧ (DstPt = 80) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = dns) ∧ (Proto = TCP)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = RST-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (SrcPt = 68)) ⇒ ((SrcIpAddr = private_p2p))
((DstPt = unknown_port) ∧ (Flags = FIN-SYN-PSH-ACK) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((DstIpAddr = public_p2p))
((DstIpAddr = private_broadcast) ∧ (DstPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-RST-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Proto = ICMP)) ⇒ ((Flags = none) ∧ (SrcPt = 0))
((DstIpAddr = private_p2p) ∧ (DstPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-SYN-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = FIN-RST-ACK)) ⇒ ((Proto = TCP))
((Flags = SYN-RST)) ⇒ ((DstIpAddr = public_p2p) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = dns) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = 53))
((DstIpAddr = public_p2p) ∧ (DstPt = unknown_port)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = SYN-RST-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = RST-PSH-ACK)) ⇒ ((Proto = TCP))
((SrcPt = 123)) ⇒ ((DstPt = 123) ∧ (Flags = none) ∧ (Proto = UDP))
((Flags = FIN-PSH-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 137))
((DstPt = 25)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = SYN) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((Flags = ACK)) ⇒ ((Proto = TCP))
((DstPt = 80)) ⇒ ((Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((Flags = FIN-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((Flags = FIN-SYN-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = unknown_port) ∧ (Flags = none)) ⇒ ((Proto = UDP))
((DstIpAddr = public_p2p) ∧ (Proto = TCP)) ⇒ ((SrcPt = unknown_port))
((Flags = none) ∧ (SrcPt = 53)) ⇒ ((Proto = UDP))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = FIN-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = dns) ∧ (Flags = FIN-SYN-PSH-ACK)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstPt = 123) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p))
((Flags = SYN-RST-PSH-ACK)) ⇒ ((Proto = TCP))
((Flags = FIN-RST-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((Flags = SYN-RST-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 53)) ⇒ ((DstIpAddr = dns) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((Flags = FIN-SYN-RST-PSH-ACK)) ⇒ ((Proto = TCP))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = 80))
((DstIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = FIN-SYN-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = 80))
((DstIpAddr = private_p2p) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((Proto = TCP))
((Flags = FIN-SYN-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((Flags = RST) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((DstPt = 80) ∧ (Flags = SYN-RST-ACK)) ⇒ ((DstIpAddr = public_p2p))
((Flags = ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((SrcPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 138) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((SrcPt = 8080)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = FIN-SYN-PSH-ACK) ∧ (Proto = TCP) ∧ (SrcIpAddr = public_p2p))
((SrcPt = 0)) ⇒ ((Flags = none))
((DstPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 138))
((DstIpAddr = public_p2p) ∧ (Flags = ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = RST) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = none) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((Flags = SYN-RST-PSH-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p) ∧ (SrcPt = unknown_port))
((Flags = FIN-RST-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((Flags = RST-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (DstPt = 67)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = none) ∧ (SrcIpAddr = dns)) ⇒ ((Proto = UDP))
((DstPt = unknown_port) ∧ (Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((DstIpAddr = public_p2p))
((SrcPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 137) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-SYN-RST-ACK)) ⇒ ((DstPt = 80) ∧ (SrcPt = unknown_port))
((SrcIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((DstIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (Proto = UDP) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((DstPt = unknown_port) ∧ (Flags = FIN-RST-PSH-ACK)) ⇒ ((DstIpAddr = private_p2p))
((Proto = UDP)) ⇒ ((Flags = none))
((DstPt = 123)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 123))
((SrcPt = 67)) ⇒ ((DstPt = 68) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((SrcPt = 443)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Proto = TCP) ∧ (SrcIpAddr = public_p2p))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-ACK)) ⇒ ((SrcPt = unknown_port))
((DstPt = unknown_port) ∧ (Flags = none) ∧ (SrcIpAddr = public_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = RST-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = RST)) ⇒ ((Proto = TCP))
((Flags = ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((Flags = FIN-RST-PSH-ACK)) ⇒ ((Proto = TCP))
((DstIpAddr = public_p2p) ∧ (Flags = RST-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((Flags = FIN-RST-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = 8080)) ⇒ ((DstIpAddr = public_p2p) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((SrcIpAddr = public_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((Flags = RST-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((Proto = TCP) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = 11)) ⇒ ((DstIpAddr = private_p2p) ∧ (Flags = none) ∧ (Proto = ICMP) ∧ (SrcIpAddr = public_p2p) ∧ (SrcPt = 0))
((Flags = SYN-RST-PSH-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((Flags = RST-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = unknown_port) ∧ (Flags = FIN-RST-ACK)) ⇒ ((DstIpAddr = private_p2p) ∧ (SrcIpAddr = public_p2p))
((Flags = SYN-PSH-ACK)) ⇒ ((Proto = TCP))
((Flags = RST) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = FIN-SYN-RST-PSH-ACK)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_broadcast) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = private_p2p))
((Flags = SYN-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstPt = 8)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = none) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
(DstIpAddr ≠ 0.0.0.0)
((Flags = ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstPt = 0)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = none) ∧ (Proto = IGMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-SYN-PSH-ACK) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = 80))
((SrcPt = 80)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Proto = TCP))
((SrcIpAddr = dns)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcPt = 53))
((DstIpAddr = private_p2p) ∧ (Flags = RST)) ⇒ ((DstPt = unknown_port))
((SrcPt = 53)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcIpAddr = dns))
((Flags = SYN-RST-PSH-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((Flags = SYN-ACK) ∧ (SrcPt = 22)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = SYN-RST-ACK) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((SrcPt = 22)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Proto = TCP))
((DstPt = unknown_port) ∧ (Flags = none) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((DstPt = unknown_port) ∧ (Flags = SYN-RST-PSH-ACK)) ⇒ ((DstIpAddr = private_p2p) ∧ (SrcIpAddr = public_p2p))
((Flags = FIN-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3))
((SrcIpAddr = 0.0.0.0)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 67) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 68))
((DstPt = 80) ∧ (Flags = FIN-SYN-RST-ACK)) ⇒ ((DstIpAddr = public_p2p))
((Flags = FIN-SYN-RST-PSH-ACK) ∧ (SrcPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (Flags = FIN-RST-PSH-ACK)) ⇒ ((DstPt = unknown_port))
((Flags = FIN-RST-ACK) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((Flags = FIN-SYN-RST-ACK)) ⇒ ((Proto = TCP))
((DstIpAddr = private_p2p) ∧ (Flags = ACK)) ⇒ ((DstPt = unknown_port))
((DstPt = 80) ∧ (Flags = ACK)) ⇒ ((DstIpAddr = public_p2p))
((Flags = FIN-PSH-ACK)) ⇒ ((Proto = TCP))
((Flags = RST-PSH-ACK) ∧ (SrcPt = 80)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 80) ∧ (Flags = RST)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 67)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 68))
