((DstIpAddr = dns)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = none) ∧ (SrcIpAddr = dns)) ⇒ ((Proto = UDP))
((DstPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 137))
((DstIpAddr = dns) ∧ (Proto = ICMP)) ⇒ ((DstPt = 3))
((Flags = FIN)) ⇒ ((Proto = TCP))
((DstIpAddr = private_p2p) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3))
((DstIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((DstPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 138))
((Proto = TCP)) ⇒ ((Flags = FIN))
((SrcIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((DstIpAddr = public_p2p))
((SrcPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 138) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = private_broadcast)) ⇒ ((Flags = none) ∧ (Proto = UDP))
((DstPt = 123) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 68)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 67))
((SrcPt = 67)) ⇒ ((DstPt = 68) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (DstPt = 67)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstPt = 3))
((SrcIpAddr = public_p2p)) ⇒ ((DstIpAddr = private_p2p))
((SrcPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 137) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstPt = 53) ∧ (Flags = none)) ⇒ ((Proto = UDP))
((DstIpAddr = dns) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3) ∧ (Proto = ICMP))
((SrcPt = 0)) ⇒ ((Flags = none))
((DstPt = 123)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 123))
((DstPt = 67)) ⇒ ((Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 68))
((DstIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((SrcIpAddr = 0.0.0.0)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 67) ∧ (Flags = none) ∧ (Proto = UDP) ∧ (SrcPt = 68))
((Proto = ICMP)) ⇒ ((Flags = none) ∧ (SrcPt = 0))
((SrcPt = 68)) ⇒ ((DstPt = 67) ∧ (Flags = none) ∧ (Proto = UDP))
((DstIpAddr = private_p2p) ∧ (SrcPt = 68)) ⇒ ((SrcIpAddr = private_p2p))
((SrcPt = 123)) ⇒ ((DstPt = 123) ∧ (Flags = none) ∧ (Proto = UDP))
((DstPt = 11)) ⇒ ((DstIpAddr = private_p2p) ∧ (Flags = none) ∧ (Proto = ICMP) ∧ (SrcIpAddr = public_p2p) ∧ (SrcPt = 0))
((Proto = IGMP)) ⇒ ((DstIpAddr = public_p2p) ∧ (DstPt = 0) ∧ (Flags = none) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((DstPt = 0)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = none) ∧ (Proto = IGMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((DstIpAddr = private_p2p) ∧ (DstPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 3)) ⇒ ((Flags = none) ∧ (Proto = ICMP) ∧ (SrcPt = 0))
((SrcIpAddr = public_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((Flags = none) ∧ (SrcPt = 53)) ⇒ ((Proto = UDP))
((Proto = UDP)) ⇒ ((Flags = none))
((DstIpAddr = public_p2p)) ⇒ ((SrcIpAddr = private_p2p))
((DstPt = 8)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = none) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
