((DstIpAddr = dns)) ⇒ ((SrcIpAddr = private_p2p))
((Flags = noflags) ∧ (SrcIpAddr = dns)) ⇒ ((Proto = UDP))
((SrcIpAddr = public_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((SrcPt = 993)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p))
((DstPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 137))
((DstIpAddr = public_p2p) ∧ (DstPt = unknown_port)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = dns) ∧ (Proto = ICMP)) ⇒ ((DstPt = 3))
((DstIpAddr = dns) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = 53))
((Flags = hasflags)) ⇒ ((Proto = TCP))
((DstIpAddr = private_p2p) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3))
((Flags = noflags) ∧ (SrcPt = unknown_port)) ⇒ ((Proto = UDP))
((DstPt = 80)) ⇒ ((Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((SrcPt = 22)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = hasflags) ∧ (Proto = TCP))
((DstIpAddr = private_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((DstPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 138))
((Proto = TCP)) ⇒ ((Flags = hasflags))
((SrcPt = 8080)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = public_p2p))
((DstPt = unknown_port) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((SrcIpAddr = dns)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcPt = 53))
((SrcIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((DstIpAddr = public_p2p))
((Proto = TCP) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((SrcPt = 138)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 138) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = public_p2p) ∧ (Proto = UDP) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = private_broadcast)) ⇒ ((Flags = noflags) ∧ (Proto = UDP))
((DstPt = 123) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstIpAddr = public_p2p))
((DstPt = 25)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = dns) ∧ (Proto = UDP)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstIpAddr = dns) ∧ (Flags = hasflags)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstPt = 68)) ⇒ ((Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 67))
((DstIpAddr = private_p2p) ∧ (Flags = noflags) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (Proto = UDP) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = public_p2p))
((DstIpAddr = private_p2p) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port)) ⇒ ((Flags = hasflags) ∧ (Proto = TCP))
((DstIpAddr = public_p2p) ∧ (Flags = hasflags)) ⇒ ((SrcPt = unknown_port))
((SrcPt = 67)) ⇒ ((DstPt = 68) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = private_p2p) ∧ (DstPt = 67)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = private_broadcast) ∧ (DstPt = unknown_port)) ⇒ ((SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p)) ⇒ ((DstPt = 3))
((SrcIpAddr = public_p2p)) ⇒ ((DstIpAddr = private_p2p))
((SrcPt = 443)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = public_p2p))
((SrcPt = 137)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 137) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcIpAddr = private_p2p))
((DstIpAddr = private_broadcast) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port) ∧ (SrcIpAddr = private_p2p))
((DstPt = 53) ∧ (Flags = noflags)) ⇒ ((Proto = UDP))
((DstPt = 993)) ⇒ ((DstIpAddr = private_p2p) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((SrcPt = 80)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (Flags = hasflags) ∧ (Proto = TCP))
((DstIpAddr = dns) ∧ (SrcPt = 0)) ⇒ ((DstPt = 3) ∧ (Proto = ICMP))
((SrcPt = 0)) ⇒ ((Flags = noflags))
((DstPt = 123)) ⇒ ((Flags = noflags) ∧ (Proto = UDP) ∧ (SrcPt = 123))
((DstPt = 67)) ⇒ ((Flags = noflags) ∧ (Proto = UDP) ∧ (SrcPt = 68))
((DstIpAddr = private_p2p) ∧ (SrcPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 443)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstPt = 22)) ⇒ ((Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstPt = unknown_port) ∧ (Flags = noflags) ∧ (SrcIpAddr = private_p2p)) ⇒ ((SrcPt = unknown_port))
((SrcIpAddr = 0.0.0.0)) ⇒ ((DstIpAddr = private_broadcast) ∧ (DstPt = 67) ∧ (Flags = noflags) ∧ (Proto = UDP) ∧ (SrcPt = 68))
((Proto = ICMP)) ⇒ ((Flags = noflags) ∧ (SrcPt = 0))
((SrcPt = 68)) ⇒ ((DstPt = 67) ∧ (Flags = noflags) ∧ (Proto = UDP))
((DstPt = unknown_port) ∧ (Flags = noflags) ∧ (SrcIpAddr = public_p2p)) ⇒ ((SrcPt = unknown_port))
((DstIpAddr = private_p2p) ∧ (SrcPt = 68)) ⇒ ((SrcIpAddr = private_p2p))
((DstIpAddr = dns) ∧ (Proto = TCP)) ⇒ ((DstPt = 53) ∧ (SrcPt = unknown_port))
((DstPt = 53)) ⇒ ((DstIpAddr = dns) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Proto = TCP)) ⇒ ((SrcPt = unknown_port))
((SrcPt = 123)) ⇒ ((DstPt = 123) ∧ (Flags = noflags) ∧ (Proto = UDP))
((DstPt = 11)) ⇒ ((DstIpAddr = private_p2p) ∧ (Flags = noflags) ∧ (Proto = ICMP) ∧ (SrcIpAddr = public_p2p) ∧ (SrcPt = 0))
((Proto = IGMP)) ⇒ ((DstIpAddr = public_p2p) ∧ (DstPt = 0) ∧ (Flags = noflags) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcIpAddr = private_p2p)) ⇒ ((Flags = hasflags) ∧ (Proto = TCP))
((DstPt = 0)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = noflags) ∧ (Proto = IGMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((DstIpAddr = private_p2p) ∧ (DstPt = 123)) ⇒ ((SrcIpAddr = public_p2p))
((DstPt = 3)) ⇒ ((Flags = noflags) ∧ (Proto = ICMP) ∧ (SrcPt = 0))
((SrcIpAddr = public_p2p) ∧ (SrcPt = 0)) ⇒ ((Proto = ICMP))
((Flags = noflags) ∧ (SrcPt = 53)) ⇒ ((Proto = UDP))
((DstPt = unknown_port) ∧ (Proto = UDP) ∧ (SrcIpAddr = public_p2p)) ⇒ ((SrcPt = unknown_port))
((DstPt = 8080)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = hasflags) ∧ (Proto = TCP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = unknown_port))
((DstIpAddr = public_p2p) ∧ (Flags = noflags) ∧ (SrcPt = unknown_port)) ⇒ ((DstPt = unknown_port))
((DstPt = unknown_port) ∧ (Flags = noflags)) ⇒ ((Proto = UDP))
((Proto = UDP)) ⇒ ((Flags = noflags))
((Flags = hasflags) ∧ (SrcIpAddr = public_p2p)) ⇒ ((DstPt = unknown_port))
((DstIpAddr = public_p2p)) ⇒ ((SrcIpAddr = private_p2p))
((DstPt = 8)) ⇒ ((DstIpAddr = public_p2p) ∧ (Flags = noflags) ∧ (Proto = ICMP) ∧ (SrcIpAddr = private_p2p) ∧ (SrcPt = 0))
((SrcPt = 53)) ⇒ ((DstIpAddr = private_p2p) ∧ (DstPt = unknown_port) ∧ (SrcIpAddr = dns))
