Implies(StrictGreaterThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0030078124', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050018730000000002', precision=53))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(137)))
LessThan(Symbol('Duration'), Float('2.004', precision=53))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(357)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(56))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(473)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), LessThan(Symbol('Bytes'), Integer(49))), Equality(Symbol('Flags'), Integer(0)))
GreaterThan(Symbol('Duration'), Float('0.0', precision=53))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(147))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Unequality(Symbol('DstPt'), Integer(137)), Unequality(Symbol('DstPt'), Integer(138))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Unequality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('Proto'), Integer(2)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0024998016000000001', precision=53)), LessThan(Symbol('Packets'), Integer(6))), Equality(Symbol('Bytes'), Integer(479)))
Implies(And(Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Equality(Symbol('Proto'), Integer(0))), Equality(Symbol('DstPt'), Integer(80)))
Implies(LessThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050072476999999998', precision=53))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(Unequality(Symbol('DstPt'), Integer(8)), Unequality(Symbol('DstPt'), Integer(137)), Unequality(Symbol('DstPt'), Integer(138))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(48)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(StrictGreaterThan(Symbol('Packets'), Integer(3)), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Unequality(Symbol('Flags'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(0)))
GreaterThan(Symbol('Packets'), Integer(1))
Implies(LessThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('DstPt'), Integer(138)))
Implies(LessThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('Proto'), Integer(2)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(357)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('DstIpAddr'), Integer(0)))
LessThan(Symbol('Flags'), Integer(1))
Implies(And(Equality(Symbol('Flags'), Integer(0)), LessThan(Symbol('Bytes'), Integer(68))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050018730000000002', precision=53))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('SrcPt'), Integer(137)))
LessThan(Symbol('Proto'), Integer(2))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(356)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(67)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(357))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), LessThan(Symbol('Packets'), Integer(2)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Bytes'), Integer(56)), LessThan(Symbol('Packets'), Integer(3))), Equality(Symbol('DstPt'), Integer(80)))
GreaterThan(Symbol('Bytes'), Integer(42))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), LessThan(Symbol('Bytes'), Integer(512))), And(GreaterThan(Symbol('Packets'), Integer(1)), LessThan(Symbol('Packets'), Integer(5))))
Implies(And(LessThan(Symbol('Duration'), Float('1.003957', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0030078124', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(357)), StrictGreaterThan(Symbol('Bytes'), Integer(147))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Unequality(Symbol('Proto'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Bytes'), Integer(56)), LessThan(Symbol('Packets'), Integer(3))), Equality(Symbol('DstPt'), Integer(80)))
LessThan(Symbol('DstPt'), Integer(60000))
Implies(And(Equality(Symbol('Proto'), Integer(1)), LessThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(2)), StrictGreaterThan(Symbol('Bytes'), Integer(162))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(210)), StrictGreaterThan(Symbol('Bytes'), Integer(67)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(2)), StrictGreaterThan(Symbol('Bytes'), Integer(162))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0024998016000000001', precision=53))), And(GreaterThan(Symbol('Bytes'), Integer(479)), LessThan(Symbol('Bytes'), Integer(545))))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(48)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(StrictGreaterThan(Symbol('Bytes'), Integer(473)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(LessThan(Symbol('Packets'), Integer(6)), And(GreaterThan(Symbol('Bytes'), Integer(42)), LessThan(Symbol('Bytes'), Integer(574))))
Implies(And(Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(82))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(148))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), LessThan(Symbol('Packets'), Integer(2)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(357)), StrictGreaterThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Proto'), Integer(2)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(StrictGreaterThan(Symbol('Packets'), Integer(5)), Equality(Symbol('Bytes'), Integer(545)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), And(GreaterThan(Symbol('Packets'), Integer(2)), LessThan(Symbol('Packets'), Integer(6))))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(82))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('Flags'), Integer(0)))
GreaterThan(Symbol('SrcIpAddr'), Integer(0))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Unequality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(137)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), And(GreaterThan(Symbol('Bytes'), Integer(112)), LessThan(Symbol('Bytes'), Integer(545))))
Implies(Unequality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0097775115000000006', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Unequality(Symbol('Flags'), Integer(0))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), LessThan(Symbol('Packets'), Integer(6))), And(GreaterThan(Symbol('Bytes'), Integer(42)), LessThan(Symbol('Bytes'), Integer(574))))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(148))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050018730000000002', precision=53))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(83)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(138)), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(356)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(473)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), LessThan(Symbol('Bytes'), Integer(512))), And(GreaterThan(Symbol('Packets'), Integer(2)), LessThan(Symbol('Packets'), Integer(5))))
GreaterThan(Symbol('SrcPt'), Integer(0))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(137)))
Implies(LessThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('DstPt'), Integer(8)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0097775115000000006', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Equality(Symbol('Proto'), Integer(0))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Bytes'), Integer(474))), Equality(Symbol('DstPt'), Integer(80)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('DstPt'), Integer(8)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0020487672', precision=53))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Unequality(Symbol('DstPt'), Integer(8)), Unequality(Symbol('DstPt'), Integer(137)), Unequality(Symbol('DstPt'), Integer(138))), Equality(Symbol('Proto'), Integer(0)))
LessThan(Symbol('Bytes'), Integer(574))
Implies(And(Equality(Symbol('Proto'), Integer(1)), LessThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('SrcPt'), Integer(137)))
LessThan(Symbol('Packets'), Integer(6))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(Unequality(Symbol('SrcPt'), Integer(137)), Unequality(Symbol('SrcPt'), Integer(138))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Unequality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), And(GreaterThan(Symbol('Packets'), Integer(1)), LessThan(Symbol('Packets'), Integer(6))))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('SrcPt'), Integer(138)))
GreaterThan(Symbol('DstPt'), Integer(0))
Implies(LessThan(Symbol('Bytes'), Integer(512)), And(GreaterThan(Symbol('Packets'), Integer(1)), LessThan(Symbol('Packets'), Integer(5))))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('1.002', precision=53)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('Proto'), Integer(1)))
Implies(StrictGreaterThan(Symbol('Bytes'), Integer(512)), And(GreaterThan(Symbol('Packets'), Integer(4)), LessThan(Symbol('Packets'), Integer(6))))
Implies(Unequality(Symbol('Proto'), Integer(1)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('DstPt'), Integer(138)))
Implies(Equality(Symbol('DstPt'), Integer(8)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(8)), Equality(Symbol('Proto'), Integer(2)))
LessThan(Symbol('SrcIpAddr'), Integer(0))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(148))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(56)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(83)), StrictGreaterThan(Symbol('Bytes'), Integer(66))), Equality(Symbol('DstPt'), Integer(22)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Bytes'), Integer(474))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(Unequality(Symbol('SrcPt'), Integer(0)), Unequality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0030078124', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(138)))
Implies(StrictGreaterThan(Symbol('Packets'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('Flags'), Integer(0))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Or(Equality(Symbol('DstPt'), Integer(8)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138))), Equality(Symbol('Flags'), Integer(0)))
GreaterThan(Symbol('DstIpAddr'), Integer(0))
Implies(And(Equality(Symbol('Proto'), Integer(0)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('DstPt'), Integer(80)))
Implies(StrictGreaterThan(Symbol('Bytes'), Integer(473)), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(56))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050454709999999997', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(209)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0479463', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(LessThan(Symbol('Bytes'), Integer(473)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), And(GreaterThan(Symbol('Bytes'), Integer(42)), LessThan(Symbol('Bytes'), Integer(574))))
Implies(Unequality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
GreaterThan(Symbol('Flags'), Integer(0))
Implies(And(LessThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(209)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('DstPt'), Integer(137)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0097775115000000006', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(80)))
Implies(LessThan(Symbol('Bytes'), Integer(474)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(208)), Unequality(Symbol('DstIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('Proto'), Integer(0)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('Proto'), Integer(1)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), LessThan(Symbol('Packets'), Integer(6))), And(GreaterThan(Symbol('Bytes'), Integer(112)), LessThan(Symbol('Bytes'), Integer(479))))
Implies(And(Unequality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(0)))
LessThan(Symbol('SrcPt'), Integer(60000))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(356))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0024998016000000001', precision=53)), LessThan(Symbol('Bytes'), Integer(512))), Equality(Symbol('Packets'), Integer(5)))
Implies(And(Equality(Symbol('SrcPt'), Integer(60000)), LessThan(Symbol('Bytes'), Integer(148)), StrictGreaterThan(Symbol('Bytes'), Integer(57))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0020487672', precision=53))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(210)), StrictGreaterThan(Symbol('Bytes'), Integer(67)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('DstPt'), Integer(8)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(356)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Unequality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('DstPt'), Integer(8)))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.00050454709999999997', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(83))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0030078124', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0020487672', precision=53))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(357)), StrictGreaterThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Bytes'), Integer(56)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('DstPt'), Integer(80)))
LessThan(Symbol('DstIpAddr'), Integer(1))
Implies(And(Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('SrcPt'), Integer(138)))
GreaterThan(Symbol('Proto'), Integer(0))
Implies(And(LessThan(Symbol('Duration'), Float('0.0039140624000000004', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0024998016000000001', precision=53))), And(GreaterThan(Symbol('Packets'), Integer(5)), LessThan(Symbol('Packets'), Integer(6))))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.001015625', precision=53)), LessThan(Symbol('Bytes'), Integer(356)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(StrictGreaterThan(Symbol('Bytes'), Integer(48)), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(149)), LessThan(Symbol('Packets'), Integer(3))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Bytes'), Integer(148)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(48)), StrictGreaterThan(Symbol('Packets'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Bytes'), Integer(474)), StrictGreaterThan(Symbol('Bytes'), Integer(209))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Unequality(Symbol('Flags'), Integer(0))), Equality(Symbol('DstPt'), Integer(80)))
Implies(StrictGreaterThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), Equality(Symbol('SrcPt'), Integer(138)))
Implies(StrictGreaterThan(Symbol('Packets'), Integer(3)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Proto'), Integer(1)), StrictGreaterThan(Symbol('Bytes'), Integer(208))), Equality(Symbol('DstPt'), Integer(138)))
Implies(And(LessThan(Symbol('Duration'), Float('1.002', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(1)), Unequality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(137)))
Implies(StrictGreaterThan(Symbol('Packets'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Bytes'), Integer(356)), StrictGreaterThan(Symbol('Bytes'), Integer(48))), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), StrictGreaterThan(Symbol('Packets'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(LessThan(Symbol('Duration'), Float('0.0097775115000000006', precision=53)), StrictGreaterThan(Symbol('Duration'), Float('0.0019570312000000002', precision=53)), Unequality(Symbol('DstIpAddr'), Integer(1))), Equality(Symbol('DstPt'), Integer(80)))
Implies(Unequality(Symbol('SrcPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(LessThan(Symbol('Duration'), Float('1.0489687999999999', precision=53)), LessThan(Symbol('Packets'), Integer(3)), StrictGreaterThan(Symbol('Bytes'), Integer(148))), Equality(Symbol('Proto'), Integer(1)))
