Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(28))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(19))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(28)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(26)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('Flags'), Integer(17)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(29)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(24)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(26))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(17))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(23))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('Flags'), Integer(4)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(26))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(23)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Unequality(Symbol('SrcIpAddr'), Integer(1))
Implies(And(Equality(Symbol('Flags'), Integer(23)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(30))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(29)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(22))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('Flags'), Integer(16)), Equality(Symbol('SrcPt'), Integer(22))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(4))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(28)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(1))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Flags'), Integer(18)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Flags'), Integer(22)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(19)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(19)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(19))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('Flags'), Integer(20)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Flags'), Integer(19)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(21)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(22))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(30))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('Flags'), Integer(23)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(31))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(19))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(18))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(30))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(22)), Equality(Symbol('Flags'), Integer(16))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(23))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('Flags'), Integer(24)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(22)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(29)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
And(Unequality(Symbol('Flags'), Integer(1)), Unequality(Symbol('Flags'), Integer(3)), Unequality(Symbol('Flags'), Integer(5)), Unequality(Symbol('Flags'), Integer(7)), Unequality(Symbol('Flags'), Integer(8)), Unequality(Symbol('Flags'), Integer(9)), Unequality(Symbol('Flags'), Integer(10)), Unequality(Symbol('Flags'), Integer(11)), Unequality(Symbol('Flags'), Integer(12)), Unequality(Symbol('Flags'), Integer(13)), Unequality(Symbol('Flags'), Integer(14)), Unequality(Symbol('Flags'), Integer(15)))
Implies(Equality(Symbol('Flags'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(30)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(21))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('Flags'), Integer(22)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(25))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(28))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(29))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('Flags'), Integer(28)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(23)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(24))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(20)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(60000))), And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(29))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(27))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Flags'), Integer(21)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Flags'), Integer(6)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(53)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(60000))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(22))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Flags'), Integer(28)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('Flags'), Integer(25)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(2)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('Flags'), Integer(16)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(80)), And(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(25)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(25))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(17)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(27))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('Flags'), Integer(30)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(21)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(22)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(80)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(80)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(19)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(4)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(22))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(16)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(16))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(30)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(29)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(20)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(23))), And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(29))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(17))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(20))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Flags'), Integer(4)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(16)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('Flags'), Integer(29)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(28))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(21)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('Flags'), Integer(20)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(30)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(20)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(21))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('Flags'), Integer(26)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(31))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(18)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(8)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Unequality(Symbol('DstIpAddr'), Integer(2))
Implies(And(Equality(Symbol('Flags'), Integer(16)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('DstPt'), Integer(0)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(27)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(80)))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcPt'), Integer(53))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(4))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(4))))
Implies(And(Equality(Symbol('Flags'), Integer(30)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(18)), Equality(Symbol('SrcPt'), Integer(22))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(22)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(22)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(30))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('Flags'), Integer(25)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(23))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('Flags'), Integer(31)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(29))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('Flags'), Integer(21)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Flags'), Integer(23)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(16))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(16))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('Flags'), Integer(25)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(28)), Equality(Symbol('SrcPt'), Integer(80))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(80)), Equality(Symbol('Flags'), Integer(4))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(67)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
