Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstPt'), Integer(67)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstPt'), Integer(138)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(22)), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Unequality(Symbol('SrcPt'), Integer(8080)))
Implies(Equality(Symbol('Proto'), Integer(1)), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('SrcPt'), Integer(123)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(68)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(123)), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('Proto'), Integer(3)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Equality(Symbol('DstPt'), Integer(68)))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(8)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(67)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(68)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Unequality(Symbol('SrcPt'), Integer(8080)))
Implies(Equality(Symbol('DstPt'), Integer(138)), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(123)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(53)), Unequality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(8)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(53)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(123)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Unequality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(8)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('DstPt'), Integer(68)))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(0)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(11)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(8)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(53)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('DstPt'), Integer(123)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(68)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(443)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(138)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(11)), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(443)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('Proto'), Integer(3)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('SrcPt'), Integer(80)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('Proto'), Integer(0)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(25)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(0)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(67)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstPt'), Integer(68)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(8)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(22)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('Proto'), Integer(3)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(123)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(123)), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(1)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(3)), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstPt'), Integer(25)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Flags'), Integer(1)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(443)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(0)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(993)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(443)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(8)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(Equality(Symbol('DstPt'), Integer(25)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(2)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('Flags'), Integer(1)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(443)), Equality(Symbol('DstPt'), Integer(68)))
Implies(Equality(Symbol('SrcPt'), Integer(53)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('Flags'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(25)), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(8)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('Flags'), Integer(1)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(3)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(80)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Unequality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(68)))
Implies(Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(0)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('Flags'), Integer(1)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Unequality(Symbol('SrcPt'), Integer(8080)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('DstPt'), Integer(3)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(80)), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(68)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(53)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(4)))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('Proto'), Integer(2)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(137)), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(Equality(Symbol('Flags'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(22)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(67)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(0)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), Equality(Symbol('Proto'), Integer(2)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('Flags'), Integer(1)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138))), Unequality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(68)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Or(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(2))))
Implies(Equality(Symbol('Flags'), Integer(1)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), Equality(Symbol('Proto'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Unequality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Unequality(Symbol('Flags'), Integer(1)))
Implies(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138))), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('Flags'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(0)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('DstPt'), Integer(11)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(3)), Unequality(Symbol('SrcPt'), Integer(8080)))
Implies(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Or(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstIpAddr'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('Proto'), Integer(1)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(8)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), Equality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('SrcPt'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(443)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(137)), Not(Or(Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('DstPt'), Integer(138)))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), Not(Or(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('SrcPt'), Integer(138)))))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Unequality(Symbol('SrcPt'), Integer(80)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Unequality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Or(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('DstPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(137)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('SrcPt'), Integer(68)), Unequality(Symbol('SrcPt'), Integer(443)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), Equality(Symbol('DstIpAddr'), Integer(0)))
