Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), LessThan(Symbol('Tsecr_2'), Symbol('Tsval_1')))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Not(Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18)))), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18))))), GreaterThan(Symbol('TcpSeq_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
And(LessThan(Symbol('IpTtl_1'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_1'), Integer(0)))
Equality(Mod(Symbol('TcpHdrLen_3'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_3'), Integer(0))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
Implies(And(Equality(Symbol('TcpAck_1'), Symbol('TcpAck_2')), Equality(Symbol('TcpAck_2'), Symbol('TcpAck_3')), Equality(Symbol('TcpFlags_1'), Integer(16)), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpFlags_3'), Integer(16))), And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3'))))
Equality(Mod(Symbol('TcpHdrLen_2'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_3'), Integer(0))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
And(LessThan(Symbol('IpTtl_3'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_3'), Integer(0)))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3')), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18)))), Not(Or(Equality(Symbol('TcpFlags_3'), Integer(1)), Equality(Symbol('TcpFlags_3'), Integer(2)), Equality(Symbol('TcpFlags_3'), Integer(17)), Equality(Symbol('TcpFlags_3'), Integer(18))))), GreaterThan(Symbol('TcpSeq_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3')), Equality(Symbol('TcpFlags_2'), Symbol('TcpFlags_3')), Equality(Symbol('TcpLen_2'), Symbol('TcpLen_3')), Equality(Symbol('TcpSeq_2'), Symbol('TcpSeq_3'))), Equality(Symbol('IpDst_2'), Symbol('IpDst_3')))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Mod(Symbol('IpHdrLen_2'), Integer(4)), Integer(0))
Equality(Mod(Symbol('TcpHdrLen_1'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('TcpLen_2'), Integer(0)), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18)))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1))))
And(LessThan(Symbol('IpTtl_2'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_2'), Integer(0)))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpLen_1'), Integer(0)), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Not(Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18))))), Equality(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Mod(Symbol('IpHdrLen_3'), Integer(4)), Integer(0))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')), Symbol('TcpWindowSize_1'))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('TcpLen_2'), Integer(0)), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18))))), Equality(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
Implies(And(Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(18)), Equality(Symbol('TcpFlags_3'), Integer(16)), StrictGreaterThan(Symbol('Tsval_1'), Integer(0)), StrictGreaterThan(Symbol('Tsval_2'), Integer(0))), And(Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2'))))
Equality(Mod(Symbol('IpHdrLen_1'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpFlags_1'), Integer(24)), Equality(Symbol('Tsval_1'), Symbol('Tsecr_2'))), Or(Equality(Symbol('TcpFlags_2'), Integer(4)), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(20)), Equality(Symbol('TcpFlags_2'), Integer(24))))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpSrc_2')), Equality(Symbol('IpSrc_1'), Symbol('IpDst_2'))), And(Equality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_2')), Equality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_2'))))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Equality(Symbol('TcpFlags_1'), Symbol('TcpFlags_2')), Equality(Symbol('TcpLen_1'), Symbol('TcpLen_2')), Equality(Symbol('TcpSeq_1'), Symbol('TcpSeq_2'))), And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2'))))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpLen_1'), Integer(0)), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18)))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1))))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')), Symbol('TcpWindowSize_3'))
Implies(And(Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('Tsval_1'), Symbol('Tsecr_2'))), And(Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1)))))
Implies(And(Equality(Symbol('TcpAck_1'), Symbol('TcpSeq_2')), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpSeq_2'), Symbol('TcpAck_1')))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(18)), Equality(Symbol('TcpFlags_3'), Integer(16))), And(Equality(Symbol('TcpSeq_3'), Symbol('TcpAck_2')), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1)))))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')), Symbol('TcpWindowSize_2'))
LessThan(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeScalefactor_3'))
Unequality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpLen_3'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Equality(Symbol('TcpSeq_1'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_2')))
LessThan(Symbol('Tsval_1'), Symbol('Tsecr_3'))
LessThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpSeq_1'), Symbol('TcpAck_2'))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_2')))
Unequality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSize_1'))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('Tsecr_2'), Symbol('Tsecr_3'))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
LessThan(Symbol('Tsecr_1'), Symbol('Tsecr_3'))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3'))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_2')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSizeValue_3'))
Equality(Symbol('TcpFlags_1'), Integer(2))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
LessThan(Symbol('TcpHdrLen_3'), Integer(0))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('IpTtl_1'), Symbol('IpTtl_2'))
Equality(Symbol('TcpDstport_1'), Symbol('TcpDstport_3'))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Integer(0))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_2'), Symbol('TcpSeq_3')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_2'))
LessThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
Unequality(Symbol('TcpDstport_1'), Symbol('TcpDstport_3'))
Unequality(Symbol('Tsval_1'), Symbol('Tsecr_3'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_2'))
Unequality(Symbol('IpDst_1'), Symbol('IpSrc_3'))
Unequality(Symbol('TcpFlags_1'), Symbol('TcpFlags_2'))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('TcpSeq_3'), Symbol('TcpAck_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSizeValue_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_3')))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpWindowSizeScalefactor_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3')))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Symbol('TcpSeq_3')))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_2'))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
LessThan(Symbol('Tsval_1'), Symbol('Tsval_2'))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpAck_2'), Symbol('TcpAck_3'))
Equality(Symbol('TcpSeq_2'), Symbol('TcpSeq_3'))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpAck_1'), Symbol('TcpSeq_3'))
StrictGreaterThan(Symbol('TcpLen_3'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpDstport_1'), Symbol('TcpDstport_2'))
StrictGreaterThan(Symbol('TcpLen_2'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('Tsecr_2'), Symbol('Tsval_3'))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
StrictGreaterThan(Symbol('TcpLen_1'), Integer(0))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('IpHdrLen_2'), Integer(0))
StrictGreaterThan(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_3'))
LessThan(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpDstport_2'), Symbol('TcpSrcport_3'))
LessThan(Symbol('Tsval_2'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_3')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_1'), Integer(1)))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_2')))
LessThan(Symbol('TcpLen_3'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('Tsecr_2'), Add(Symbol('Tsecr_1'), Symbol('Tsval_1')))
Unequality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_3'))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('TcpFlags_1'), Symbol('TcpFlags_2'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSizeValue_3'))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_3'))
LessThan(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpDstport_2'), Symbol('TcpDstport_3'))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('Tsecr_1'), Symbol('Tsval_2'))
Unequality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpSrcport_1'), Symbol('TcpSrcport_2'))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpSeq_1'), Integer(1))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpSeq_3'), Integer(1))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpFlags_2'), Symbol('TcpFlags_3'))
StrictGreaterThan(Symbol('Tsecr_1'), Symbol('Tsecr_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('TcpSeq_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('Tsval_1'), Symbol('Tsval_3'))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Integer(0))
LessThan(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('TcpSeq_1'), Symbol('TcpAck_1'))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpFlags_3'), Integer(17))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
LessThan(Symbol('TcpLen_1'), Integer(0))
Equality(Symbol('TcpLen_3'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_2'))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('Tsecr_2'), Symbol('Tsval_3'))
Equality(Symbol('TcpSeq_2'), Symbol('TcpAck_3'))
StrictGreaterThan(Symbol('TcpSeq_2'), Integer(1))
LessThan(Symbol('IpHdrLen_1'), Integer(0))
Equality(Symbol('IpSrc_1'), Symbol('IpDst_3'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpLen_2'), Symbol('IpLen_3'))
Unequality(Symbol('IpDst_1'), Symbol('IpDst_3'))
Unequality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpFlags_2'), Integer(17))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('TcpWindowSize_2'), Symbol('TcpWindowSize_3'))
Unequality(Symbol('IpSrc_1'), Symbol('IpDst_3'))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpSrcport_2'), Symbol('TcpSrcport_3'))
Equality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSizeValue_2'))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_3')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('IpSrc_2'), Symbol('IpDst_3'))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
StrictGreaterThan(Symbol('IpHdrLen_3'), Integer(0))
StrictGreaterThan(Symbol('TcpWindowSizeScalefactor_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2')))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpLen_1'), Add(Symbol('TcpLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpLen_1'), Symbol('TcpLen_2'))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Equality(Symbol('Tsval_1'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_2')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3'))
Equality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Integer(1)))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpFlags_3'), Integer(24))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2'))
LessThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_3')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1)))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpFlags_1'), Integer(18))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('Tsecr_1'), Symbol('Tsval_2'))
Equality(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
LessThan(Symbol('IpLen_3'), Integer(0))
Equality(Symbol('TcpSrcport_2'), Symbol('TcpSrcport_3'))
Unequality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_2'))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_2'))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpAck_1'), Symbol('TcpAck_3'))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Integer(0))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_2')))
Equality(Symbol('TcpSeq_1'), Symbol('TcpSeq_2'))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1)))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('Tsecr_1'), Symbol('Tsval_3'))
StrictGreaterThan(Symbol('Tsecr_3'), Add(Symbol('Tsecr_1'), Symbol('Tsval_2')))
Equality(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3'))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpSeq_2'), Symbol('TcpAck_2'))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_1'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_3')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_2')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpFlags_2'), Integer(24))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpSeq_1'), Symbol('TcpSeq_2'))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpSeq_2'), Symbol('TcpAck_2'))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('Tsval_2'), Symbol('Tsecr_3'))
Unequality(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('Tsval_2'), Symbol('Tsecr_3'))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Unequality(Symbol('TcpSeq_2'), Add(Symbol('TcpSeq_1'), Integer(1)))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('Tsecr_1'), Symbol('Tsecr_2'))
LessThan(Symbol('IpLen_1'), Symbol('IpLen_3'))
LessThan(Symbol('IpHdrLen_2'), Integer(0))
StrictGreaterThan(Symbol('Tsecr_2'), Symbol('Tsval_3'))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('Tsecr_1'), Symbol('Tsecr_2'))
LessThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_3'))
LessThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpFlags_1'), Integer(2))
StrictGreaterThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpSrcport_2'), Symbol('TcpDstport_3'))
Unequality(Symbol('IpLen_1'), Symbol('IpLen_2'))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
LessThan(Symbol('IpLen_1'), Symbol('IpLen_2'))
LessThan(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSizeValue_3'))
Unequality(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSizeValue_3'))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('IpDst_1'), Symbol('IpDst_2'))
Unequality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
Equality(Symbol('TcpFlags_2'), Integer(16))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('Tsval_1'), Symbol('Tsval_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
Equality(Symbol('TcpAck_1'), Symbol('TcpAck_2'))
Unequality(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpFlags_1'), Integer(24))
Equality(Symbol('TcpAck_2'), Symbol('TcpSeq_3'))
LessThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('Tsval_1'), Symbol('Tsecr_2'))
Unequality(Symbol('TcpLen_1'), Symbol('TcpLen_3'))
StrictGreaterThan(Symbol('TcpAck_1'), Integer(1))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Integer(1)))
Unequality(Symbol('TcpLen_2'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_3')))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpAck_2'), Integer(1))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('IpTtl_1'), Symbol('IpTtl_2'))
LessThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpFlags_1'), Integer(24))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
LessThan(Symbol('Tsval_1'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_3')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpSrcport_1'), Symbol('TcpSrcport_3'))
Equality(Symbol('TcpLen_2'), Symbol('TcpLen_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Equality(Symbol('Tsval_1'), Symbol('Tsecr_3'))
Unequality(Symbol('TcpSeq_2'), Symbol('TcpAck_3'))
StrictGreaterThan(Symbol('TcpLen_1'), Symbol('TcpLen_3'))
Equality(Symbol('TcpWindowSizeValue_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
Equality(Symbol('IpLen_1'), Symbol('IpLen_2'))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSizeValue_2'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_2')))
Equality(Symbol('TcpAck_2'), Symbol('TcpAck_3'))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_1')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpHdrLen_1'), Integer(0))
LessThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_2')))
Equality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpLen_2'), Symbol('TcpLen_3'))
StrictGreaterThan(Symbol('TcpSeq_3'), Integer(1))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Equality(Symbol('Tsecr_1'), Symbol('Tsecr_2'))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_1'), Integer(1)))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpSrcport_1'), Symbol('TcpSrcport_2'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_3')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpFlags_3'), Integer(16))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpAck_3'), Integer(1))
Unequality(Symbol('TcpWindowSize_2'), Symbol('TcpWindowSize_3'))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('Tsecr_2'), Symbol('Tsval_3'))
LessThan(Symbol('IpLen_2'), Integer(0))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
LessThan(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2'))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_2'), Symbol('TcpSeq_3')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpSeq_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
StrictGreaterThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_3')))
Equality(Symbol('Tsval_1'), Symbol('Tsval_2'))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpLen_1'), Symbol('TcpLen_2'))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpTtl_1'), Symbol('IpTtl_2'))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_3'))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpSeq_1'), Symbol('TcpAck_3'))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Equality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('IpLen_1'), Integer(0))
StrictGreaterThan(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2'))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_3')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3'))
Unequality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('IpTtl_2'), Symbol('IpTtl_3'))
LessThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpLen_2'), Symbol('TcpLen_3'))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpFlags_1'), Integer(16))
Unequality(Symbol('TcpWindowSizeScalefactor_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2')))
Equality(Symbol('TcpLen_2'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('Tsval_1'), Symbol('Tsval_2'))
LessThan(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_2')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpFlags_1'), Integer(17))
Unequality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
Unequality(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2'))
LessThan(Symbol('Tsecr_2'), Symbol('Tsecr_3'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpLen_2'), Symbol('TcpLen_3'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('IpLen_2'), Symbol('IpLen_3'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_3'))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpDstport_2'), Symbol('TcpSrcport_3'))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpSeq_1'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_2')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Equality(Symbol('IpTtl_2'), Symbol('IpTtl_3'))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_2'))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpSeq_3'), Symbol('TcpAck_3'))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
Unequality(Symbol('TcpWindowSizeScalefactor_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3')))
Equality(Symbol('IpLen_1'), Symbol('IpLen_3'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpLen_1'), Symbol('TcpLen_3'))
Equality(Symbol('Tsecr_1'), Symbol('Tsval_3'))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSizeValue_2'))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_2'), Integer(1)))
Equality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_2')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('IpSrc_2'), Symbol('IpSrc_3'))
Unequality(Symbol('TcpAck_2'), Symbol('TcpSeq_3'))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('IpDst_1'), Symbol('IpDst_3'))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Symbol('TcpWindowSize_3'))
LessThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_3')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_1'), Symbol('TcpSeq_2'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_1'), Integer(1)))
Equality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpFlags_2'), Symbol('TcpFlags_3'))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('Tsecr_1'), Integer(0))
Unequality(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeScalefactor_3'))
LessThan(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpLen_3'), Integer(0))
LessThan(Symbol('TcpAck_1'), Integer(1))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpDst_1'), Symbol('IpSrc_3'))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('TcpFlags_1'), Symbol('TcpFlags_3'))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpSeq_1'), Symbol('TcpSeq_3'))
StrictGreaterThan(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_2'))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpFlags_2'), Integer(16))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Equality(Symbol('IpDst_1'), Symbol('IpDst_2'))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_2'), Integer(1)))
Equality(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2'))
LessThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1)))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('IpDst_2'), Symbol('IpSrc_3'))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('Tsval_2'), Symbol('Tsecr_3'))
Equality(Symbol('TcpLen_1'), Add(Symbol('TcpLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpLen_1'), Symbol('TcpLen_2'))
LessThan(Symbol('TcpSeq_1'), Integer(1))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_2'), Integer(1)))
LessThan(Symbol('IpTtl_1'), Symbol('IpTtl_2'))
Equality(Symbol('TcpLen_1'), Symbol('TcpLen_2'))
Unequality(Symbol('TcpSeq_1'), Symbol('TcpSeq_3'))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_3')))
Equality(Symbol('Tsecr_1'), Symbol('Tsecr_3'))
StrictGreaterThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('Tsecr_2'), Symbol('Tsecr_3'))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('Tsval_1'), Symbol('Tsval_3'))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('IpLen_2'), Symbol('IpLen_3'))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpFlags_2'), Integer(24))
LessThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpFlags_2'), Integer(18))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSize_2'), Symbol('TcpWindowSize_3'))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Symbol('TcpSeq_2')))
Equality(Symbol('TcpSeq_1'), Symbol('TcpAck_2'))
Equality(Symbol('IpSrc_1'), Symbol('IpDst_2'))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('Tsecr_1'), Symbol('Tsecr_2'))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
LessThan(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
LessThan(Symbol('TcpLen_1'), Add(Symbol('TcpLen_2'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('IpHdrLen_1'), Integer(0))
LessThan(Symbol('Tsecr_1'), Symbol('Tsval_3'))
Unequality(Symbol('TcpFlags_1'), Integer(17))
StrictGreaterThan(Symbol('TcpLen_1'), Add(Symbol('TcpLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('IpDst_1'), Symbol('IpSrc_2'))
Unequality(Symbol('TcpFlags_1'), Symbol('TcpFlags_3'))
Equality(Symbol('TcpDstport_1'), Symbol('TcpDstport_2'))
StrictGreaterThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
LessThan(Symbol('IpTtl_1'), Symbol('IpTtl_3'))
LessThan(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_2')))
Unequality(Symbol('TcpAck_1'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
Equality(Symbol('IpSrc_2'), Symbol('IpDst_3'))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_3'))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_3')))
Unequality(Symbol('IpTtl_1'), Symbol('IpTtl_3'))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpSrc_1'), Symbol('IpSrc_3'))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Symbol('TcpSeq_3')))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('IpTtl_1'), Symbol('IpTtl_3'))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('IpSrc_1'), Symbol('IpDst_2'))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('IpDst_2'), Symbol('IpSrc_3'))
LessThan(Symbol('Tsecr_3'), Add(Symbol('Tsecr_1'), Symbol('Tsval_2')))
LessThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_2')))
StrictGreaterThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpAck_2'), Integer(1))
LessThan(Symbol('IpLen_2'), Symbol('IpLen_3'))
Equality(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeScalefactor_3'))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('IpSrc_1'), Symbol('IpSrc_3'))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('Tsval_2'), Symbol('Tsval_3'))
Equality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpFlags_1'), Integer(16))
Unequality(Symbol('TcpAck_1'), Symbol('TcpSeq_2'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('IpTtl_2'), Symbol('IpTtl_3'))
Unequality(Symbol('IpSrc_1'), Symbol('IpSrc_2'))
Unequality(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3'))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpAck_1'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
LessThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSizeValue_2'))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
LessThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_2')))
Equality(Symbol('TcpWindowSizeScalefactor_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2'))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2'))
Unequality(Symbol('IpTtl_2'), Symbol('IpTtl_3'))
Unequality(Symbol('Tsecr_2'), Symbol('Tsecr_3'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpLen_3'), Integer(0))
Unequality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('IpLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3'))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_2'))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_2')))
Unequality(Symbol('TcpFlags_2'), Integer(18))
Equality(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('IpLen_1'), Symbol('IpLen_2'))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Equality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_3')))
StrictGreaterThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_3'))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
LessThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpHdrLen_2'), Integer(0))
Unequality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_3'))
StrictGreaterThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSize_1'))
Equality(Symbol('IpDst_2'), Symbol('IpDst_3'))
Equality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpLen_1'), Symbol('TcpLen_3'))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('Tsval_2'), Symbol('Tsval_3'))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('IpTtl_1'), Symbol('IpTtl_3'))
Unequality(Symbol('Tsval_1'), Symbol('Tsecr_2'))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Equality(Symbol('TcpSrcport_1'), Symbol('TcpSrcport_3'))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpWindowSizeValue_3'), Add(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')))
LessThan(Symbol('Tsval_1'), Symbol('Tsval_3'))
LessThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_3'))
Equality(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpAck_1'), Add(Symbol('TcpSeq_1'), Integer(1)))
Equality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
Unequality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_2'))
Unequality(Symbol('Tsecr_1'), Symbol('Tsecr_3'))
Equality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpFlags_1'), Integer(18))
Equality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_2'))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('Tsval_1'), Symbol('Tsecr_3'))
Unequality(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
LessThan(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_2')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpSeq_2'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('Tsecr_3'), Add(Symbol('Tsecr_1'), Symbol('Tsval_2')))
Unequality(Symbol('Tsecr_1'), Symbol('Tsval_3'))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_3'))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_2')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('Tsval_1'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_2')))
Equality(Symbol('TcpSeq_1'), Symbol('TcpAck_3'))
LessThan(Symbol('Tsval_2'), Symbol('Tsval_3'))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
Equality(Symbol('IpHdrLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpLen_2')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
Equality(Symbol('TcpDstport_2'), Symbol('TcpDstport_3'))
Equality(Symbol('TcpSeq_2'), Add(Symbol('TcpSeq_1'), Integer(1)))
LessThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
Unequality(Symbol('Tsval_1'), Symbol('Tsval_2'))
Unequality(Symbol('Tsval_2'), Symbol('Tsval_3'))
Equality(Symbol('TcpWindowSizeValue_1'), Symbol('TcpWindowSizeValue_3'))
LessThan(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('Tsval_2'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_3')))
LessThan(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
StrictGreaterThan(Symbol('IpLen_3'), Integer(0))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_2')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_3')))
LessThan(Symbol('IpLen_1'), Integer(0))
Equality(Symbol('TcpFlags_2'), Integer(17))
Equality(Symbol('IpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_1')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3'))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2'))
Equality(Symbol('Tsecr_2'), Add(Symbol('Tsecr_1'), Symbol('Tsval_1')))
LessThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('Tsval_1'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_2')))
Unequality(Symbol('TcpAck_1'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
LessThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Equality(Symbol('TcpSeq_1'), Symbol('TcpAck_1'))
LessThan(Symbol('Tsval_1'), Symbol('Tsecr_2'))
Equality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
LessThan(Symbol('TcpLen_2'), Add(Symbol('TcpLen_1'), Symbol('TcpLen_3')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('Tsecr_1'), Symbol('Tsval_2'))
Unequality(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSizeValue_2'))
StrictGreaterThan(Symbol('TcpAck_3'), Integer(1))
StrictGreaterThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('Tsval_2'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_3')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpSeq_2'), Integer(1)))
StrictGreaterThan(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpSrcport_2'), Symbol('TcpDstport_3'))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_1')))
LessThan(Symbol('IpHdrLen_3'), Integer(0))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
Equality(Symbol('TcpFlags_3'), Integer(17))
Equality(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('Tsval_2'), Add(Symbol('Tsecr_1'), Symbol('Tsecr_3')))
LessThan(Symbol('IpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_2')))
Unequality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpLen_1'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeScalefactor_3'))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1)))
Equality(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_3')))
LessThan(Symbol('Tsecr_1'), Symbol('Tsval_2'))
Equality(Symbol('Tsecr_3'), Add(Symbol('Tsecr_1'), Symbol('Tsval_2')))
Unequality(Symbol('TcpSeq_2'), Symbol('TcpSeq_3'))
Equality(Symbol('TcpWindowSizeValue_1'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpWindowSize_3'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Unequality(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3'))
Unequality(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2'))
Unequality(Symbol('TcpAck_2'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
LessThan(Symbol('IpLen_2'), Add(Symbol('IpLen_3'), Symbol('TcpLen_2')))
StrictGreaterThan(Symbol('Tsval_1'), Symbol('Tsecr_2'))
StrictGreaterThan(Symbol('IpLen_1'), Symbol('IpLen_3'))
Equality(Symbol('TcpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('TcpLen_3'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSizeValue_2'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('TcpWindowSize_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_3')))
Equality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_1')))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_3')))
StrictGreaterThan(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_3'), Symbol('TcpLen_1')))
Unequality(Symbol('IpLen_1'), Symbol('IpLen_3'))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1')))
Unequality(Symbol('TcpWindowSize_2'), Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_1')))
Unequality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_3'), Symbol('TcpLen_3')))
Unequality(Symbol('TcpHdrLen_2'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_3')))
Unequality(Symbol('TcpSeq_3'), Add(Symbol('TcpAck_3'), Symbol('TcpSeq_1')))
LessThan(Symbol('TcpSeq_2'), Integer(1))
Equality(Symbol('TcpFlags_3'), Integer(24))
Equality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpAck_2')))
Unequality(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_3'))
StrictGreaterThan(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_2'), Symbol('TcpHdrLen_2')))
LessThan(Symbol('TcpWindowSize_1'), Symbol('TcpWindowSize_3'))
Equality(Symbol('TcpAck_1'), Symbol('TcpAck_3'))
Unequality(Symbol('IpDst_2'), Symbol('IpDst_3'))
StrictGreaterThan(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
Equality(Symbol('IpDst_1'), Symbol('IpSrc_2'))
Equality(Symbol('TcpWindowSizeValue_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')))
Equality(Symbol('IpHdrLen_2'), Add(Symbol('IpHdrLen_1'), Symbol('TcpLen_1')))
Unequality(Symbol('TcpWindowSize_2'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_1')))
Equality(Symbol('TcpHdrLen_3'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
StrictGreaterThan(Symbol('IpLen_2'), Integer(0))
Unequality(Symbol('TcpAck_3'), Add(Symbol('TcpAck_1'), Symbol('TcpSeq_1')))
LessThan(Symbol('TcpLen_2'), Integer(0))
Unequality(Symbol('TcpLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpHdrLen_2')))
StrictGreaterThan(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSize_3')))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_3')))
LessThan(Symbol('IpLen_3'), Add(Symbol('IpLen_2'), Symbol('TcpLen_2')))
Equality(Symbol('TcpHdrLen_2'), Add(Symbol('TcpHdrLen_1'), Symbol('TcpLen_2')))
Unequality(Symbol('TcpFlags_3'), Integer(16))
Unequality(Symbol('IpLen_1'), Add(Symbol('IpLen_3'), Symbol('TcpLen_3')))
LessThan(Symbol('Tsval_2'), Symbol('Tsecr_3'))
Unequality(Symbol('IpLen_3'), Add(Symbol('IpHdrLen_3'), Symbol('TcpHdrLen_2')))
Equality(Symbol('TcpWindowSize_1'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_2')))
LessThan(Symbol('TcpWindowSizeScalefactor_3'), Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeScalefactor_2')))
LessThan(Symbol('TcpWindowSize_1'), Add(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSize_3')))
Unequality(Symbol('TcpAck_1'), Symbol('TcpAck_2'))
Equality(Symbol('TcpAck_1'), Symbol('TcpSeq_3'))
Unequality(Symbol('TcpHdrLen_1'), Add(Symbol('TcpHdrLen_2'), Symbol('TcpLen_1')))
