Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(4))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Proto'), Integer(3)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(67))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(25)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(5353)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(5353))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(60000))), And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(68))), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1))), Equality(Symbol('SrcPt'), Integer(60000)))
Unequality(Symbol('SrcIpAddr'), Integer(1))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(11)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcPt'), Integer(993)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Unequality(Symbol('DstIpAddr'), Integer(2))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(60000))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(Equality(Symbol('SrcPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('SrcPt'), Integer(67)), And(Equality(Symbol('DstPt'), Integer(68)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('DstIpAddr'), Integer(0)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(1))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstIpAddr'), Integer(1)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(Equality(Symbol('DstPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(138))))
Implies(Equality(Symbol('DstPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(137))))
Implies(Equality(Symbol('SrcPt'), Integer(137)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(137)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(2))), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('DstPt'), Integer(443)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(8082)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('Flags'), Integer(1)))
Implies(And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('Flags'), Integer(0))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('SrcPt'), Integer(8082)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Proto'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('DstPt'), Integer(67)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('SrcPt'), Integer(53)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(4))))
Implies(Equality(Symbol('SrcPt'), Integer(587)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(22)), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcPt'), Integer(68)), And(Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('SrcPt'), Integer(60000)))
Implies(And(Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(3)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('SrcPt'), Integer(8000)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), And(Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(60000)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('Flags'), Integer(1))), And(Equality(Symbol('DstPt'), Integer(53)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(8080)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(3))))
Implies(Equality(Symbol('DstPt'), Integer(68)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(67))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(60000))), Equality(Symbol('DstPt'), Integer(53)))
Implies(And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('SrcIpAddr'), Integer(0))), Equality(Symbol('DstIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(5353)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('DstPt'), Integer(5353)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcPt'), Integer(0))), And(Equality(Symbol('DstPt'), Integer(3)), Equality(Symbol('Proto'), Integer(2))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('Proto'), Integer(2)))
Implies(Equality(Symbol('DstPt'), Integer(587)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(2)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(67)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(68))))
Implies(Equality(Symbol('DstPt'), Integer(8000)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('Proto'), Integer(2)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(3)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(8)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(2)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)))
Implies(Equality(Symbol('DstPt'), Integer(123)), And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcPt'), Integer(123))))
Implies(And(Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('SrcPt'), Integer(53))), Equality(Symbol('Proto'), Integer(1)))
Implies(Equality(Symbol('DstPt'), Integer(0)), And(Equality(Symbol('DstIpAddr'), Integer(3)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(3)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(445)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(123))), Equality(Symbol('SrcIpAddr'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(138)), And(Equality(Symbol('DstIpAddr'), Integer(1)), Equality(Symbol('DstPt'), Integer(138)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1)), Equality(Symbol('SrcIpAddr'), Integer(0))))
Implies(Equality(Symbol('SrcIpAddr'), Integer(4)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcPt'), Integer(53))))
Implies(Equality(Symbol('DstPt'), Integer(445)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(0))), Equality(Symbol('DstPt'), Integer(3)))
Implies(Equality(Symbol('SrcPt'), Integer(80)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('DstPt'), Integer(80)), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0)), Equality(Symbol('SrcIpAddr'), Integer(0)), Equality(Symbol('SrcPt'), Integer(60000))))
Implies(Equality(Symbol('SrcPt'), Integer(22)), And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('SrcPt'), Integer(123)), And(Equality(Symbol('DstPt'), Integer(123)), Equality(Symbol('Flags'), Integer(0)), Equality(Symbol('Proto'), Integer(1))))
Implies(And(Equality(Symbol('DstIpAddr'), Integer(0)), Equality(Symbol('DstPt'), Integer(60000)), Equality(Symbol('SrcIpAddr'), Integer(0))), And(Equality(Symbol('Flags'), Integer(1)), Equality(Symbol('Proto'), Integer(0))))
Implies(Equality(Symbol('DstIpAddr'), Integer(4)), Equality(Symbol('SrcIpAddr'), Integer(0)))
Implies(Equality(Symbol('SrcPt'), Integer(0)), Equality(Symbol('Flags'), Integer(0)))
Implies(Equality(Symbol('Proto'), Integer(1)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(1)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(2)), GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(1)), GreaterThan(Mul(Integer(1500), Symbol('Packets')), Symbol('Bytes')))
GreaterThan(Mul(Integer(65535), Symbol('Packets')), Symbol('Bytes'))
LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes'))
Implies(Equality(Symbol('Proto'), Integer(1)), LessThan(Mul(Integer(8), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(2)), LessThan(Mul(Integer(64), Symbol('Packets')), Symbol('Bytes')))
Implies(Equality(Symbol('Proto'), Integer(0)), LessThan(Mul(Integer(42), Symbol('Packets')), Symbol('Bytes')))
