Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), LessThan(Symbol('Tsecr_2'), Symbol('Tsval_1')))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Not(Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18)))), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18))))), GreaterThan(Symbol('TcpSeq_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Symbol('IpLen_1'), Add(Symbol('IpHdrLen_1'), Symbol('TcpHdrLen_1'), Symbol('TcpLen_1')))
And(LessThan(Symbol('IpTtl_1'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_1'), Integer(0)))
Equality(Mod(Symbol('TcpHdrLen_3'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_3'), Integer(0))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
Implies(And(Equality(Symbol('TcpAck_1'), Symbol('TcpAck_2')), Equality(Symbol('TcpAck_2'), Symbol('TcpAck_3')), Equality(Symbol('TcpFlags_1'), Integer(16)), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpFlags_3'), Integer(16))), And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3'))))
Equality(Mod(Symbol('TcpHdrLen_2'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_3'), Integer(0))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
And(LessThan(Symbol('IpTtl_3'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_3'), Integer(0)))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3')), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18)))), Not(Or(Equality(Symbol('TcpFlags_3'), Integer(1)), Equality(Symbol('TcpFlags_3'), Integer(2)), Equality(Symbol('TcpFlags_3'), Integer(17)), Equality(Symbol('TcpFlags_3'), Integer(18))))), GreaterThan(Symbol('TcpSeq_3'), Add(Symbol('TcpLen_2'), Symbol('TcpSeq_2'))))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_2'), Symbol('IpSrc_3')), Equality(Symbol('TcpFlags_2'), Symbol('TcpFlags_3')), Equality(Symbol('TcpLen_2'), Symbol('TcpLen_3')), Equality(Symbol('TcpSeq_2'), Symbol('TcpSeq_3'))), Equality(Symbol('IpDst_2'), Symbol('IpDst_3')))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Mod(Symbol('IpHdrLen_2'), Integer(4)), Integer(0))
Equality(Mod(Symbol('TcpHdrLen_1'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('TcpLen_2'), Integer(0)), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18)))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1))))
And(LessThan(Symbol('IpTtl_2'), Integer(255)), StrictGreaterThan(Symbol('IpTtl_2'), Integer(0)))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpLen_1'), Integer(0)), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Not(Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18))))), Equality(Symbol('TcpAck_2'), Symbol('TcpSeq_1')))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), StrictGreaterThan(Symbol('TcpLen_1'), Integer(0)), StrictGreaterThan(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpLen_1'), Symbol('TcpSeq_1'))))
Equality(Mod(Symbol('IpHdrLen_3'), Integer(4)), Integer(0))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_1'), Symbol('TcpWindowSizeValue_1')), Symbol('TcpWindowSize_1'))
Implies(And(Equality(Symbol('IpSrc_2'), Symbol('IpDst_3')), Equality(Symbol('IpSrc_3'), Symbol('IpDst_2')), Equality(Symbol('TcpLen_2'), Integer(0)), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2')), Not(Or(Equality(Symbol('TcpFlags_2'), Integer(1)), Equality(Symbol('TcpFlags_2'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(18))))), Equality(Symbol('TcpAck_3'), Symbol('TcpSeq_2')))
Implies(And(Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(18)), Equality(Symbol('TcpFlags_3'), Integer(16)), StrictGreaterThan(Symbol('Tsval_1'), Integer(0)), StrictGreaterThan(Symbol('Tsval_2'), Integer(0))), And(Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Equality(Symbol('Tsecr_3'), Symbol('Tsval_2'))))
Equality(Mod(Symbol('IpHdrLen_1'), Integer(4)), Integer(0))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpFlags_1'), Integer(24)), Equality(Symbol('Tsval_1'), Symbol('Tsecr_2'))), Or(Equality(Symbol('TcpFlags_2'), Integer(4)), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpFlags_2'), Integer(17)), Equality(Symbol('TcpFlags_2'), Integer(20)), Equality(Symbol('TcpFlags_2'), Integer(24))))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpSrc_2')), Equality(Symbol('IpSrc_1'), Symbol('IpDst_2'))), And(Equality(Symbol('TcpDstport_1'), Symbol('TcpSrcport_2')), Equality(Symbol('TcpSrcport_1'), Symbol('TcpDstport_2'))))
Implies(And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2')), Equality(Symbol('TcpFlags_1'), Symbol('TcpFlags_2')), Equality(Symbol('TcpLen_1'), Symbol('TcpLen_2')), Equality(Symbol('TcpSeq_1'), Symbol('TcpSeq_2'))), And(Equality(Symbol('IpDst_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_1'), Symbol('IpSrc_2'))))
Implies(And(Equality(Symbol('IpSrc_1'), Symbol('IpDst_2')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpLen_1'), Integer(0)), Equality(Symbol('Tsecr_2'), Symbol('Tsval_1')), Or(Equality(Symbol('TcpFlags_1'), Integer(1)), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('TcpFlags_1'), Integer(18)))), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1))))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_3'), Symbol('TcpWindowSizeValue_3')), Symbol('TcpWindowSize_3'))
Implies(And(Equality(Symbol('TcpFlags_1'), Integer(17)), Equality(Symbol('Tsval_1'), Symbol('Tsecr_2'))), And(Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1)))))
Implies(And(Equality(Symbol('TcpAck_1'), Symbol('TcpSeq_2')), Equality(Symbol('TcpFlags_2'), Integer(16)), Equality(Symbol('TcpLen_2'), Integer(0))), Equality(Symbol('TcpSeq_2'), Symbol('TcpAck_1')))
Implies(And(Equality(Symbol('IpDst_2'), Symbol('IpSrc_1')), Equality(Symbol('IpSrc_2'), Symbol('IpDst_1')), Equality(Symbol('TcpFlags_1'), Integer(2)), Equality(Symbol('TcpFlags_2'), Integer(18)), Equality(Symbol('TcpFlags_3'), Integer(16))), And(Equality(Symbol('TcpSeq_3'), Symbol('TcpAck_2')), Equality(Symbol('TcpAck_2'), Add(Symbol('TcpSeq_1'), Integer(1))), Equality(Symbol('TcpAck_3'), Add(Symbol('TcpSeq_2'), Integer(1)))))
Equality(Mul(Symbol('TcpWindowSizeScalefactor_2'), Symbol('TcpWindowSizeValue_2')), Symbol('TcpWindowSize_2'))
LessThan(Symbol('IpLen_1'), Integer(1500))
GreaterThan(Symbol('TcpSeq_1'), Integer(0))
LessThan(Symbol('TcpWindowSizeScalefactor_3'), Integer(512))
LessThan(Symbol('TcpHdrLen_2'), Integer(52))
GreaterThan(Symbol('TcpAck_3'), Integer(1))
LessThan(Symbol('TcpAck_1'), Integer(25013410))
GreaterThan(Symbol('IpTtl_2'), Integer(56))
GreaterThan(Symbol('Tsval_1'), Integer(565270055))
GreaterThan(Symbol('IpTtl_3'), Integer(56))
LessThan(Symbol('TcpWindowSizeScalefactor_2'), Integer(512))
GreaterThan(Symbol('TcpWindowSize_3'), Integer(66880))
GreaterThan(Symbol('TcpWindowSizeScalefactor_2'), Integer(1))
GreaterThan(Symbol('TcpWindowSizeValue_1'), Integer(2050))
LessThan(Symbol('TcpWindowSize_1'), Integer(1049600))
GreaterThan(Symbol('IpHdrLen_3'), Integer(20))
GreaterThan(Symbol('Tsval_3'), Integer(565270162))
LessThan(Symbol('TcpSeq_3'), Integer(25013410))
LessThan(Symbol('TcpWindowSizeValue_2'), Integer(65535))
LessThan(Symbol('IpHdrLen_1'), Integer(20))
GreaterThan(Symbol('TcpWindowSizeValue_2'), Integer(2050))
LessThan(Symbol('IpLen_3'), Integer(1500))
GreaterThan(Symbol('TcpSeq_3'), Integer(1))
LessThan(Symbol('IpHdrLen_2'), Integer(20))
GreaterThan(Symbol('TcpLen_2'), Integer(0))
GreaterThan(Symbol('TcpLen_1'), Integer(0))
GreaterThan(Symbol('IpLen_1'), Integer(52))
GreaterThan(Symbol('TcpWindowSizeValue_3'), Integer(2050))
LessThan(Symbol('TcpAck_3'), Integer(25013411))
LessThan(Symbol('IpTtl_2'), Integer(64))
LessThan(Symbol('IpTtl_3'), Integer(64))
GreaterThan(Symbol('TcpHdrLen_2'), Integer(32))
LessThan(Symbol('TcpLen_1'), Integer(1448))
LessThan(Symbol('TcpSeq_1'), Integer(25013410))
GreaterThan(Symbol('TcpAck_2'), Integer(1))
LessThan(Symbol('IpTtl_1'), Integer(64))
GreaterThan(Symbol('IpHdrLen_1'), Integer(20))
GreaterThan(Symbol('IpTtl_1'), Integer(56))
LessThan(Symbol('TcpSeq_2'), Integer(25013410))
LessThan(Symbol('Tsecr_1'), Integer(2516246074))
LessThan(Symbol('TcpWindowSizeScalefactor_1'), Integer(512))
GreaterThan(Symbol('TcpWindowSize_1'), Integer(65535))
GreaterThan(Symbol('TcpHdrLen_1'), Integer(32))
GreaterThan(Symbol('TcpSeq_2'), Integer(0))
LessThan(Symbol('TcpLen_2'), Integer(1448))
LessThan(Symbol('Tsval_1'), Integer(2516246074))
LessThan(Symbol('TcpWindowSize_2'), Integer(1049600))
GreaterThan(Symbol('TcpLen_3'), Integer(0))
LessThan(Symbol('Tsval_2'), Integer(2516246074))
LessThan(Symbol('TcpWindowSize_3'), Integer(1049600))
GreaterThan(Symbol('TcpAck_1'), Integer(0))
LessThan(Symbol('TcpHdrLen_3'), Integer(52))
LessThan(Symbol('TcpWindowSizeValue_1'), Integer(65535))
LessThan(Symbol('TcpHdrLen_1'), Integer(52))
LessThan(Symbol('Tsval_3'), Integer(2516246074))
LessThan(Symbol('Tsecr_2'), Integer(2516246074))
LessThan(Symbol('Tsecr_3'), Integer(2516246074))
LessThan(Symbol('TcpLen_3'), Integer(1448))
GreaterThan(Symbol('IpHdrLen_2'), Integer(20))
GreaterThan(Symbol('TcpWindowSizeScalefactor_3'), Integer(32))
LessThan(Symbol('IpHdrLen_3'), Integer(20))
GreaterThan(Symbol('Tsecr_3'), Integer(565270162))
LessThan(Symbol('IpLen_2'), Integer(1500))
GreaterThan(Symbol('Tsval_2'), Integer(565270162))
GreaterThan(Symbol('TcpFlags_3'), Integer(0))
GreaterThan(Symbol('TcpWindowSizeScalefactor_1'), Integer(1))
LessThan(Symbol('TcpFlags_1'), Integer(24))
LessThan(Symbol('TcpWindowSizeValue_3'), Integer(5068))
LessThan(Symbol('TcpAck_2'), Integer(25013410))
GreaterThan(Symbol('Tsecr_2'), Integer(565270055))
GreaterThan(Symbol('TcpHdrLen_3'), Integer(32))
LessThan(Symbol('TcpFlags_3'), Integer(24))
GreaterThan(Symbol('TcpFlags_1'), Integer(0))
GreaterThan(Symbol('TcpFlags_2'), Integer(0))
GreaterThan(Symbol('IpLen_3'), Integer(52))
LessThan(Symbol('TcpFlags_2'), Integer(24))
GreaterThan(Symbol('IpLen_2'), Integer(52))
GreaterThan(Symbol('TcpWindowSize_2'), Integer(65535))
GreaterThan(Symbol('Tsecr_1'), Integer(0))
